services:
  - type: web
    name: whatsapp-clone
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      pip install shutil subprocess
      python build_frontend.py
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
